name: Exploit Workflow

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to exploit'
        required: true

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Execute exploit
        run: python3 exploit.py -u ${{ github.event.inputs.target }}
